# Generated by Django 6.0.3 on 2026-08-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_no_show_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendance_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
