# Generated by Django 6.0.3 on 2026-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_attendance_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='encrypted_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='encrypted_prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='encrypted_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='prescription',
            field=models.TextField(blank=True),
        ),
    ]
