# Generated by Django 6.0.3 on 2026-08-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_medicalreport_encrypted_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='encrypted_report_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
