# Generated by Django 6.0.3 on 2026-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email_lookup',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='encrypted_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='encrypted_dob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='encrypted_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='encrypted_gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='encrypted_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='encrypted_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='phone_lookup',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
